### ISSUE TITLE
Weird issues trying to boot up gtkcord4

### ISSUE THREAD

**Issue by NightMare-Vortex** [diamondburned/gtkcord4#179]
Trying to boot up from the .desktop file fails and gives me a: `The name so.libdb.gtkcord4 was not provided by any .service files`
although using it from the comand line works

installed from `gtkcord4-git` on the AUR

System info:
Operating System: Arch Linux 
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.3-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 12 × 12th Gen Intel® Core™ i7-1255U
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: Acer
Product Name: Aspire A514-55G
System Version: V1.17

**Comment by aaannestad** [comment]
Same issue, came here from the AUR as a request to put this upstream. It was suggested to me to rename `/usr/share/applications/so.libdb.gtkcord4.desktop`to `/usr/share/applications/gtkcord4.desktop`; that caused the error popup to go away but gtkcord4 still doesn't open.

Calling `gtkcord4` from the command line works fine, though.

KDE versions are the same as yours except Qt is at 5.15.11, and since I'm on Manjaro my kernel is 6.1.55-1-MANJARO.

**Comment by diamondburned** [comment]
`gtkcord4-git` appears to be out of date [on this line](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gtkcord4-git#n5)?

@txtsd

**Comment by txtsd** [comment]
@diamondburned That's how the AUR's -git packages are. The pkgver is not bumped until there is a breaking change. It builds the latest version and updates the version when installing correctly.

I was hoping you would know what that KDE based error is, because I'm unable to find how to rectify it. Launching from the desktop file works fine in other DEs.

**Comment by aaannestad** [comment]
Also worth noting that I'm having the issue with all three AUR packages, not just `gtkcord4-git`.  Currently I'm using just `gtkcord4`.

**Comment by txtsd** [comment]
That's why I suggested reporting upstream (here). The arch packages just (build and) package the provided files. And this issue seems exclusive to KDE.

**Comment by diamondburned** [comment]
Oh, I didn't notice the KDE. We have a KDE-related issue in #119, maybe that's related? I don't really know what's going on in KDE either.

**Comment by NightMare-Vortex** [comment]
Yeah I really don't get what KDE is waffling.
and even trying to get around this with this desktop file, causes plasma to ***crash*** and restart
```toml
[Desktop Entry]
Name=gtkcord4
GenericName=Discord Chat
Comment=A Discord client in Go and GTK4
Exec=zsh -c 'nohup gtkcord4 >/dev/null 2>&1 &; disown %1; exit;'
Icon=gtkcord4
Terminal=false
Type=Application
Categories=GNOME;GTK;Network;Chat;InstantMessaging;
StartupNotify=true
DBusActivatable=true
X-GNOME-UsesNotifications=true
X-Purism-FormFactor=Workstation;Mobile;
```
I'm closing the issue here and opening on upstream to plasma
